services:
  db:
    image: postgres:16
    container_name: cathori-db
    environment:
      POSTGRES_DB: cathori
      POSTGRES_USER: cathori
      POSTGRES_PASSWORD: cathori1234
    ports:
      - "5432:5432"
    volumes:
      - cathori-db-data:/var/lib/postgresql/data

volumes:
  cathori-db-data: