spring.application.name=backend

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/cathori
spring.datasource.username=cathori
spring.datasource.password=cathori1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

